### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Surfoo** [adv-lab/geocaching-adventure-labs-doc#1]
Hello,

I have a question, can we discuss in private?

**Comment by adv-lab** [comment]
Yea sure, I don't think Github has private messaging though, so what's you're preferred method?

**Comment by Surfoo** [comment]
Yes, by email : https://pwpush.com/en/p/uze4tmtvzjte2c0a

**Comment by adv-lab** [comment]
It tells me that link has expired.

**Comment by Surfoo** [comment]
https://pwpush.com/en/p/i1tf81vq5nqdmf2h
